clc;

% Load Data
path = 'E:\Research 1 - Copula with index\Matlab codes';
filename = 'original_dataset.xlsx';
fullpath = fullfile(path, filename);
data = xlsread(fullpath, 'C2:D493');

R = data(:, 1);
T = data(:, 2);

% Create figure with two y-axes
figure;

% Plot R (Monthly Avg. Rainfall) and T (Monthly Avg. Temperature) on the same y-axis
yyaxis left;
ylim([0 40])
plot(R, 'color', 'blue');
xlabel('Year', 'Interpreter', 'latex');
ylabel('Monthly Avg. Rainfall (mm/day)', 'Interpreter', 'latex');
hold on;
yVals = [2.73, 4.11];
line([1, length(R)], repmat(yVals, 2, 1), 'LineStyle', '--', 'Color', 'blue');  % Add dashed lines
set(gca, ...
    'Box'         , 'on'     , ...
    'ticklabelInterpreter', 'latex',...
    'FontSize'   , 12 , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.1 .1 .1], ...
    'YColor'      , [.1 .1 .1], ...
    'LineWidth'   , 0.6 , 'XColor', 'black', 'YColor', 'black');

% Plot T (Monthly Avg. Temperature) on the same y-axis
yyaxis right;
ylim([10 40])
plot(T, 'color', 'red'); % Use a different color (e.g., red) for the second plot
ylabel('Monthly Avg. Temperature ($^\circ$C)', 'Interpreter', 'latex');
hold on;
yVals = [21, 37];
line([1, length(T)], repmat(yVals, 2, 1), 'LineStyle', '--', 'LineWidth', 1,'Color', 'red');  % Add dashed lines
set(gca, ...
    'Box'         , 'on'     , ...
    'ticklabelInterpreter', 'latex',...
    'FontSize'   , 12 , ...
    'TickDir'     , 'out'     , ...
    'TickLength'  , [.02 .02] , ...
    'XMinorTick'  , 'on'      , ...
    'YMinorTick'  , 'on'      , ...
    'XColor'      , [.1 .1 .1], ...
    'YColor'      , [.1 .1 .1], ...
    'LineWidth'   , 0.6 , 'XColor', 'black', 'YColor', 'black');



hold off;
