% 
% 
% %font
% set( gca                       , ...
%     'FontName'   , 'Helvetica' );
% set([hTitle, hXLabel, hYLabel], ...
%     'FontName'   , 'AvantGarde','FontSize'   , 20);
% set([hXLabel, hYLabel,hLegend]  , ...
%     'FontSize'   , 18         ,'Interpreter','latex' );
% set( hTitle                    , ...
%     'FontSize'   , 18          , ...
%     'FontWeight' , 'bold'      );

%box
set(gca, ...
  'Box'         , 'on'     , ...
   'FontSize'   , 24 , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'XColor'      , [.3 .3 .3], ...
  'YColor'      , [.3 .3 .3], ...
    'LineWidth'   , 0.5   , ...
    'TickLabelInterpreter','latex' ,...
    'DefaultTextInterpreter','latex');
